export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      companies: { Row: { id: string; name: string; slug: string | null; status: 'active' | 'inactive'; org_number: string | null; industry_type: string; operational_model: string; timezone: string; language_code: string; region_code: string | null; created_at: string; updated_at: string } }
      company_settings: { Row: { company_id: string; active_modules: string[]; ui_label_set: string | null; default_maps_provider: string; allow_impersonation: boolean; created_at: string; updated_at: string } }
      profiles: { Row: { id: string; email: string | null; full_name: string | null; phone: string | null; platform_role: 'owner' | 'platform_admin' | 'support_admin' | 'billing_admin' | 'compliance_admin' | null; created_at: string; updated_at: string } }
      company_memberships: { Row: { id: string; company_id: string; user_id: string; role: 'company_admin' | 'operations_manager' | 'planner' | 'supervisor' | 'dispatcher' | 'team_lead' | 'staff' | 'contractor' | 'read_only'; status: 'invited' | 'active' | 'disabled'; is_default: boolean; invited_by: string | null; created_at: string; updated_at: string; archived_at: string | null } }
      company_invitations: { Row: { id: string; company_id: string; email: string; full_name: string | null; role: string; status: string; token: string; message: string | null; invited_by: string | null; accepted_by: string | null; accepted_at: string | null; cancelled_at: string | null; expires_at: string; created_at: string; updated_at: string } }
      company_role_permissions: { Row: { id: string; company_id: string; role: string; permission_key: string; is_allowed: boolean; source: string; created_at: string; updated_at: string } }
      teams: { Row: { id: string; company_id: string; name: string; code: string | null; description: string | null; status: 'active' | 'inactive'; team_lead_staff_profile_id: string | null; area_label: string | null; created_at: string; updated_at: string; archived_at: string | null } }
      team_memberships: { Row: { id: string; team_id: string; membership_id: string; is_primary: boolean; created_at: string; updated_at: string } }
      audit_logs: { Row: { id: string; company_id: string | null; actor_user_id: string | null; action: string; entity_type: string; entity_id: string | null; metadata: Json; ip_address: string | null; user_agent: string | null; created_at: string } }
      industry_types: { Row: { id: string; code: string; name: string; description: string | null; sort_order: number; is_active: boolean; created_at: string; updated_at: string } }
      operational_models: { Row: { id: string; code: string; name: string; description: string | null; sort_order: number; is_active: boolean; created_at: string; updated_at: string } }
      platform_modules: { Row: { id: string; code: string; name: string; description: string | null; is_core: boolean; sort_order: number; created_at: string; updated_at: string } }
      company_modules: { Row: { id: string; company_id: string; module_code: string; status: string; enabled_at: string | null; config: Json; created_at: string; updated_at: string } }
      company_feature_flags: { Row: { id: string; company_id: string; flag_key: string; is_enabled: boolean; config: Json; created_at: string; updated_at: string } }
      ui_label_sets: { Row: { id: string; industry_code: string; label_key: string; label_singular: string; label_plural: string; created_at: string; updated_at: string } }
      industry_entity_presets: { Row: { id: string; industry_code: string; entity_code: string; label_singular: string; label_plural: string; description: string | null; sort_order: number; is_active: boolean; created_at: string; updated_at: string } }
      entity_types: { Row: { id: string; company_id: string; code: string; label_singular: string; label_plural: string; description: string | null; source: string; source_preset_id: string | null; is_active: boolean; sort_order: number; created_at: string; updated_at: string; archived_at: string | null } }
      entity_type_fields: { Row: { id: string; entity_type_id: string; field_key: string; label: string; field_type: string; is_required: boolean; is_sensitive: boolean; config: Json; placeholder: string | null; help_text: string | null; sort_order: number; created_at: string; updated_at: string; archived_at: string | null } }
      staff_profiles: { Row: { id: string; company_id: string; membership_id: string | null; primary_team_id: string | null; full_name: string; email: string | null; phone: string | null; employee_id: string | null; job_title: string | null; staff_kind: string; employment_type: string | null; status: string; transport_mode: string; start_address: string | null; end_address: string | null; max_hours_per_day: number | null; max_travel_minutes_per_day: number | null; notes: string | null; created_by: string | null; updated_by: string | null; created_at: string; updated_at: string; archived_at: string | null } }
      staff_languages: { Row: { id: string; staff_profile_id: string; language_code: string; proficiency: string; created_at: string } }
      staff_licenses: { Row: { id: string; staff_profile_id: string; license_type: string; license_number: string | null; valid_from: string | null; valid_until: string | null; status: string; notes: string | null; created_at: string; updated_at: string } }
      staff_status_history: { Row: { id: string; staff_profile_id: string; old_status: string | null; new_status: string; reason: string | null; changed_by: string | null; created_at: string } }
      resource_types: { Row: { id: string; company_id: string; code: string; name: string; description: string | null; is_active: boolean; created_at: string; updated_at: string; archived_at: string | null } }
      resource_assets: { Row: { id: string; company_id: string; resource_type_id: string | null; assigned_staff_id: string | null; assigned_team_id: string | null; name: string; asset_tag: string | null; status: string; location_label: string | null; notes: string | null; created_by: string | null; updated_by: string | null; created_at: string; updated_at: string; archived_at: string | null } }
      resource_assignments: { Row: { id: string; company_id: string; resource_asset_id: string; staff_profile_id: string | null; team_id: string | null; assigned_from: string; assigned_until: string | null; status: string; notes: string | null; created_by: string | null; created_at: string } }
      entities: { Row: { id: string; company_id: string; entity_type_id: string; primary_team_id: string | null; name: string; external_id: string | null; status: string; priority: string; summary: string | null; instructions: string | null; sensitive_notes: string | null; custom_fields: Json; created_by: string | null; updated_by: string | null; created_at: string; updated_at: string; archived_at: string | null } }
      entity_addresses: { Row: { id: string; entity_id: string; label: string; street: string | null; postal_code: string | null; city: string | null; country_code: string; latitude: number | null; longitude: number | null; access_instructions: string | null; is_primary: boolean; created_at: string; updated_at: string } }
      entity_contacts: { Row: { id: string; entity_id: string; name: string; role_label: string | null; email: string | null; phone: string | null; is_primary: boolean; notes: string | null; created_at: string; updated_at: string } }
      entity_notes: { Row: { id: string; entity_id: string; company_id: string; author_user_id: string | null; note: string; visibility: string; created_at: string } }
      entity_documents: { Row: { id: string; entity_id: string; company_id: string; file_name: string; storage_path: string; mime_type: string | null; file_size_bytes: number | null; document_type: string | null; description: string | null; status: string; uploaded_by: string | null; created_at: string; archived_at: string | null } }
      entity_status_history: { Row: { id: string; entity_id: string; company_id: string; old_status: string | null; new_status: string; reason: string | null; changed_by: string | null; created_at: string } }
      entity_relations: { Row: { id: string; company_id: string; parent_entity_id: string; child_entity_id: string; relation_type: string; notes: string | null; created_by: string | null; created_at: string; archived_at: string | null } }
    }
  }
}
