export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      companies: { Row: { id: string; name: string; slug: string | null; status: 'active' | 'inactive'; org_number: string | null; industry_type: string; operational_model: string; timezone: string; language_code: string; region_code: string | null; created_at: string; updated_at: string } }
      company_settings: { Row: { company_id: string; active_modules: string[]; ui_label_set: string | null; default_maps_provider: string; allow_impersonation: boolean; created_at: string; updated_at: string } }
      profiles: { Row: { id: string; email: string | null; full_name: string | null; phone: string | null; platform_role: 'owner' | 'platform_admin' | 'support_admin' | 'billing_admin' | 'compliance_admin' | null; created_at: string; updated_at: string } }
      company_memberships: { Row: { id: string; company_id: string; user_id: string; role: 'company_admin' | 'operations_manager' | 'planner' | 'supervisor' | 'dispatcher' | 'team_lead' | 'staff' | 'contractor' | 'read_only'; status: 'invited' | 'active' | 'disabled'; is_default: boolean; invited_by: string | null; created_at: string; updated_at: string; archived_at: string | null } }
      teams: { Row: { id: string; company_id: string; name: string; code: string | null; description: string | null; status: 'active' | 'inactive'; created_at: string; updated_at: string; archived_at: string | null } }
      team_memberships: { Row: { id: string; team_id: string; membership_id: string; is_primary: boolean; created_at: string; updated_at: string } }
      audit_logs: { Row: { id: string; company_id: string | null; actor_user_id: string | null; action: string; entity_type: string; entity_id: string | null; metadata: Json; ip_address: string | null; user_agent: string | null; created_at: string } }
      industry_types: { Row: { id: string; code: string; name: string; description: string | null; sort_order: number; is_active: boolean; created_at: string; updated_at: string } }
      operational_models: { Row: { id: string; code: string; name: string; description: string | null; sort_order: number; is_active: boolean; created_at: string; updated_at: string } }
      platform_modules: { Row: { id: string; code: string; name: string; description: string | null; is_core: boolean; sort_order: number; created_at: string; updated_at: string } }
      company_modules: { Row: { id: string; company_id: string; module_code: string; status: string; enabled_at: string | null; config: Json; created_at: string; updated_at: string } }
      entity_types: { Row: { id: string; company_id: string; code: string; label_singular: string; label_plural: string; description: string | null; source: string; source_preset_id: string | null; is_active: boolean; sort_order: number; created_at: string; updated_at: string; archived_at: string | null } }
      entity_type_fields: { Row: { id: string; entity_type_id: string; field_key: string; label: string; field_type: string; is_required: boolean; is_sensitive: boolean; config: Json; sort_order: number; created_at: string; updated_at: string } }
      staff_profiles: { Row: { id: string; company_id: string; membership_id: string | null; primary_team_id: string | null; full_name: string; email: string | null; phone: string | null; employee_id: string | null; job_title: string | null; staff_kind: string; employment_type: string | null; status: string; transport_mode: string; start_address: string | null; end_address: string | null; max_hours_per_day: number | null; max_travel_minutes_per_day: number | null; notes: string | null; created_by: string | null; updated_by: string | null; created_at: string; updated_at: string; archived_at: string | null } }
      resource_types: { Row: { id: string; company_id: string; code: string; name: string; description: string | null; is_active: boolean; created_at: string; updated_at: string; archived_at: string | null } }
      resource_assets: { Row: { id: string; company_id: string; resource_type_id: string | null; assigned_staff_id: string | null; assigned_team_id: string | null; name: string; asset_tag: string | null; status: string; location_label: string | null; notes: string | null; created_by: string | null; updated_by: string | null; created_at: string; updated_at: string; archived_at: string | null } }
      entities: { Row: { id: string; company_id: string; entity_type_id: string; primary_team_id: string | null; name: string; external_id: string | null; status: string; priority: string; summary: string | null; instructions: string | null; sensitive_notes: string | null; custom_fields: Json; created_by: string | null; updated_by: string | null; created_at: string; updated_at: string; archived_at: string | null } }
      entity_addresses: { Row: { id: string; entity_id: string; label: string; street: string | null; postal_code: string | null; city: string | null; country_code: string; latitude: number | null; longitude: number | null; access_instructions: string | null; is_primary: boolean; created_at: string; updated_at: string } }
      entity_contacts: { Row: { id: string; entity_id: string; name: string; role_label: string | null; email: string | null; phone: string | null; is_primary: boolean; notes: string | null; created_at: string; updated_at: string } }
    }
  }
}
